{Released under MIT licence see LICENCE file, Copyright (c) 2022 sebeksd}
{File based on: https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes}

unit VK_Codes;

interface

type
  TKeyDirection = (kdUnknown, kdUp, kdDown);

  TVK_KeyCode = record
    VK_Name: string;
    VK_Description: string;
  end;

function VK_CodeInfo(const lVK_Code: Byte): TVK_KeyCode;

implementation

uses
  Math;

const
  cALL_KEY_CODES: array [1..254] of TVK_KeyCode =
  (
    (VK_Name: 'VK_LBUTTON'; VK_Description: 'Left mouse button'),
    (VK_Name: 'VK_RBUTTON'; VK_Description: 'Right mouse button'),
    (VK_Name: 'VK_CANCEL'; VK_Description: 'Control-break processing'),
    (VK_Name: 'VK_MBUTTON'; VK_Description: 'Middle mouse button (three-button mouse)'),
    (VK_Name: 'VK_XBUTTON1'; VK_Description: 'X1 mouse button'),
    (VK_Name: 'VK_XBUTTON2'; VK_Description: 'X2 mouse button'),
    (VK_Name: ''; VK_Description: 'Undefined'),
    (VK_Name: 'VK_BACK'; VK_Description: 'BACKSPACE key'),
    (VK_Name: 'VK_TAB'; VK_Description: 'TAB key'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: ''),
    (VK_Name: 'VK_CLEAR'; VK_Description: 'CLEAR key'),
    (VK_Name: 'VK_RETURN'; VK_Description: 'ENTER key'),
    (VK_Name: ''; VK_Description: 'Undefined'),
    (VK_Name: ''; VK_Description: ''),
    (VK_Name: 'VK_SHIFT'; VK_Description: 'SHIFT key'),
    (VK_Name: 'VK_CONTROL'; VK_Description: 'CTRL key'),
    (VK_Name: 'VK_MENU'; VK_Description: 'ALT key'),
    (VK_Name: 'VK_PAUSE'; VK_Description: 'PAUSE key'),
    (VK_Name: 'VK_CAPITAL'; VK_Description: 'CAPS LOCK key'),
    (VK_Name: 'VK_KANA'; VK_Description: 'IME Kana mode/Hangul mode'),
    (VK_Name: 'VK_IME_ON'; VK_Description: 'IME On'),
    (VK_Name: 'VK_JUNJA'; VK_Description: 'IME Junja mode'),
    (VK_Name: 'VK_FINAL'; VK_Description: 'IME final mode'),
    (VK_Name: 'VK_HANJA'; VK_Description: 'IME Hanja mode/Kanji mode'),
    (VK_Name: 'VK_IME_OFF'; VK_Description: 'IME Off'),
    (VK_Name: 'VK_ESCAPE'; VK_Description: 'ESC key'),
    (VK_Name: 'VK_CONVERT'; VK_Description: 'IME convert'),
    (VK_Name: 'VK_NONCONVERT'; VK_Description: 'IME nonconvert'),
    (VK_Name: 'VK_ACCEPT'; VK_Description: 'IME accept'),
    (VK_Name: 'VK_MODECHANGE'; VK_Description: 'IME mode change request'),
    (VK_Name: 'VK_SPACE'; VK_Description: 'SPACEBAR'),
    (VK_Name: 'VK_PRIOR'; VK_Description: 'PAGE UP key'),
    (VK_Name: 'VK_NEXT'; VK_Description: 'PAGE DOWN key'),
    (VK_Name: 'VK_END'; VK_Description: 'END key'),
    (VK_Name: 'VK_HOME'; VK_Description: 'HOME key'),
    (VK_Name: 'VK_LEFT'; VK_Description: 'LEFT ARROW key'),
    (VK_Name: 'VK_UP'; VK_Description: 'UP ARROW key'),
    (VK_Name: 'VK_RIGHT'; VK_Description: 'RIGHT ARROW key'),
    (VK_Name: 'VK_DOWN'; VK_Description: 'DOWN ARROW key'),
    (VK_Name: 'VK_SELECT'; VK_Description: 'SELECT key'),
    (VK_Name: 'VK_PRINT'; VK_Description: 'PRINT key'),
    (VK_Name: 'VK_EXECUTE'; VK_Description: 'EXECUTE key'),
    (VK_Name: 'VK_SNAPSHOT'; VK_Description: 'PRINT SCREEN key'),
    (VK_Name: 'VK_INSERT'; VK_Description: 'INS key'),
    (VK_Name: 'VK_DELETE'; VK_Description: 'DEL key'),
    (VK_Name: 'VK_HELP'; VK_Description: 'HELP key'),
    (VK_Name: ''; VK_Description: '0 key'),
    (VK_Name: ''; VK_Description: '1 key'),
    (VK_Name: ''; VK_Description: '2 key'),
    (VK_Name: ''; VK_Description: '3 key'),
    (VK_Name: ''; VK_Description: '4 key'),
    (VK_Name: ''; VK_Description: '5 key'),
    (VK_Name: ''; VK_Description: '6 key'),
    (VK_Name: ''; VK_Description: '7 key'),
    (VK_Name: ''; VK_Description: '8 key'),
    (VK_Name: ''; VK_Description: '9 key'),
    (VK_Name: ''; VK_Description: 'Undefined'),
    (VK_Name: ''; VK_Description: 'Undefined'),
    (VK_Name: ''; VK_Description: 'Undefined'),
    (VK_Name: ''; VK_Description: 'Undefined'),
    (VK_Name: ''; VK_Description: 'Undefined'),
    (VK_Name: ''; VK_Description: 'Undefined'),
    (VK_Name: ''; VK_Description: 'Undefined'),
    (VK_Name: ''; VK_Description: 'A key'),
    (VK_Name: ''; VK_Description: 'B key'),
    (VK_Name: ''; VK_Description: 'C key'),
    (VK_Name: ''; VK_Description: 'D key'),
    (VK_Name: ''; VK_Description: 'E key'),
    (VK_Name: ''; VK_Description: 'F key'),
    (VK_Name: ''; VK_Description: 'G key'),
    (VK_Name: ''; VK_Description: 'H key'),
    (VK_Name: ''; VK_Description: 'I key'),
    (VK_Name: ''; VK_Description: 'J key'),
    (VK_Name: ''; VK_Description: 'K key'),
    (VK_Name: ''; VK_Description: 'L key'),
    (VK_Name: ''; VK_Description: 'M key'),
    (VK_Name: ''; VK_Description: 'N key'),
    (VK_Name: ''; VK_Description: 'O key'),
    (VK_Name: ''; VK_Description: 'P key'),
    (VK_Name: ''; VK_Description: 'Q key'),
    (VK_Name: ''; VK_Description: 'R key'),
    (VK_Name: ''; VK_Description: 'S key'),
    (VK_Name: ''; VK_Description: 'T key'),
    (VK_Name: ''; VK_Description: 'U key'),
    (VK_Name: ''; VK_Description: 'V key'),
    (VK_Name: ''; VK_Description: 'W key'),
    (VK_Name: ''; VK_Description: 'X key'),
    (VK_Name: ''; VK_Description: 'Y key'),
    (VK_Name: ''; VK_Description: 'Z key'),
    (VK_Name: 'VK_LWIN'; VK_Description: 'Left Windows key (Natural keyboard)'),
    (VK_Name: 'VK_RWIN'; VK_Description: 'Right Windows key (Natural keyboard)'),
    (VK_Name: 'VK_APPS'; VK_Description: 'Applications key (Natural keyboard)'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: 'VK_SLEEP'; VK_Description: 'Computer Sleep key'),
    (VK_Name: 'VK_NUMPAD0'; VK_Description: 'Numeric keypad 0 key'),
    (VK_Name: 'VK_NUMPAD1'; VK_Description: 'Numeric keypad 1 key'),
    (VK_Name: 'VK_NUMPAD2'; VK_Description: 'Numeric keypad 2 key'),
    (VK_Name: 'VK_NUMPAD3'; VK_Description: 'Numeric keypad 3 key'),
    (VK_Name: 'VK_NUMPAD4'; VK_Description: 'Numeric keypad 4 key'),
    (VK_Name: 'VK_NUMPAD5'; VK_Description: 'Numeric keypad 5 key'),
    (VK_Name: 'VK_NUMPAD6'; VK_Description: 'Numeric keypad 6 key'),
    (VK_Name: 'VK_NUMPAD7'; VK_Description: 'Numeric keypad 7 key'),
    (VK_Name: 'VK_NUMPAD8'; VK_Description: 'Numeric keypad 8 key'),
    (VK_Name: 'VK_NUMPAD9'; VK_Description: 'Numeric keypad 9 key'),
    (VK_Name: 'VK_MULTIPLY'; VK_Description: 'Multiply key'),
    (VK_Name: 'VK_ADD'; VK_Description: 'Add key'),
    (VK_Name: 'VK_SEPARATOR'; VK_Description: 'Separator key'),
    (VK_Name: 'VK_SUBTRACT'; VK_Description: 'Subtract key'),
    (VK_Name: 'VK_DECIMAL'; VK_Description: 'Decimal key'),
    (VK_Name: 'VK_DIVIDE'; VK_Description: 'Divide key'),
    (VK_Name: 'VK_F1'; VK_Description: 'F1 key'),
    (VK_Name: 'VK_F2'; VK_Description: 'F2 key'),
    (VK_Name: 'VK_F3'; VK_Description: 'F3 key'),
    (VK_Name: 'VK_F4'; VK_Description: 'F4 key'),
    (VK_Name: 'VK_F5'; VK_Description: 'F5 key'),
    (VK_Name: 'VK_F6'; VK_Description: 'F6 key'),
    (VK_Name: 'VK_F7'; VK_Description: 'F7 key'),
    (VK_Name: 'VK_F8'; VK_Description: 'F8 key'),
    (VK_Name: 'VK_F9'; VK_Description: 'F9 key'),
    (VK_Name: 'VK_F10'; VK_Description: 'F10 key'),
    (VK_Name: 'VK_F11'; VK_Description: 'F11 key'),
    (VK_Name: 'VK_F12'; VK_Description: 'F12 key'),
    (VK_Name: 'VK_F13'; VK_Description: 'F13 key'),
    (VK_Name: 'VK_F14'; VK_Description: 'F14 key'),
    (VK_Name: 'VK_F15'; VK_Description: 'F15 key'),
    (VK_Name: 'VK_F16'; VK_Description: 'F16 key'),
    (VK_Name: 'VK_F17'; VK_Description: 'F17 key'),
    (VK_Name: 'VK_F18'; VK_Description: 'F18 key'),
    (VK_Name: 'VK_F19'; VK_Description: 'F19 key'),
    (VK_Name: 'VK_F20'; VK_Description: 'F20 key'),
    (VK_Name: 'VK_F21'; VK_Description: 'F21 key'),
    (VK_Name: 'VK_F22'; VK_Description: 'F22 key'),
    (VK_Name: 'VK_F23'; VK_Description: 'F23 key'),
    (VK_Name: 'VK_F24'; VK_Description: 'F24 key'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: ''),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: 'VK_NUMLOCK'; VK_Description: 'NUM LOCK key'),
    (VK_Name: 'VK_SCROLL'; VK_Description: 'SCROLL LOCK key'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: 'VK_LSHIFT'; VK_Description: 'Left SHIFT key'),
    (VK_Name: 'VK_RSHIFT'; VK_Description: 'Right SHIFT key'),
    (VK_Name: 'VK_LCONTROL'; VK_Description: 'Left CONTROL key'),
    (VK_Name: 'VK_RCONTROL'; VK_Description: 'Right CONTROL key'),
    (VK_Name: 'VK_LMENU'; VK_Description: 'Left MENU key'),
    (VK_Name: 'VK_RMENU'; VK_Description: 'Right MENU key'),
    (VK_Name: 'VK_BROWSER_BACK'; VK_Description: 'Browser Back key'),
    (VK_Name: 'VK_BROWSER_FORWARD'; VK_Description: 'Browser Forward key'),
    (VK_Name: 'VK_BROWSER_REFRESH'; VK_Description: 'Browser Refresh key'),
    (VK_Name: 'VK_BROWSER_STOP'; VK_Description: 'Browser Stop key'),
    (VK_Name: 'VK_BROWSER_SEARCH'; VK_Description: 'Browser Search key'),
    (VK_Name: 'VK_BROWSER_FAVORITES'; VK_Description: 'Browser Favorites key'),
    (VK_Name: 'VK_BROWSER_HOME'; VK_Description: 'Browser Start and Home key'),
    (VK_Name: 'VK_VOLUME_MUTE'; VK_Description: 'Volume Mute key'),
    (VK_Name: 'VK_VOLUME_DOWN'; VK_Description: 'Volume Down key'),
    (VK_Name: 'VK_VOLUME_UP'; VK_Description: 'Volume Up key'),
    (VK_Name: 'VK_MEDIA_NEXT_TRACK'; VK_Description: 'Next Track key'),
    (VK_Name: 'VK_MEDIA_PREV_TRACK'; VK_Description: 'Previous Track key'),
    (VK_Name: 'VK_MEDIA_STOP'; VK_Description: 'Stop Media key'),
    (VK_Name: 'VK_MEDIA_PLAY_PAUSE'; VK_Description: 'Play/Pause Media key'),
    (VK_Name: 'VK_LAUNCH_MAIL'; VK_Description: 'Start Mail key'),
    (VK_Name: 'VK_LAUNCH_MEDIA_SELECT'; VK_Description: 'Select Media key'),
    (VK_Name: 'VK_LAUNCH_APP1'; VK_Description: 'Start Application 1 key'),
    (VK_Name: 'VK_LAUNCH_APP2'; VK_Description: 'Start Application 2 key'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: 'VK_OEM_1'; VK_Description: 'Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ";:" key'),
    (VK_Name: 'VK_OEM_PLUS'; VK_Description: 'For any country/region, the "+" key'),
    (VK_Name: 'VK_OEM_COMMA'; VK_Description: 'For any country/region, the "," key'),
    (VK_Name: 'VK_OEM_MINUS'; VK_Description: 'For any country/region, the "-" key'),
    (VK_Name: 'VK_OEM_PERIOD'; VK_Description: 'For any country/region, the "." key'),
    (VK_Name: 'VK_OEM_2'; VK_Description: 'Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the "/?" key'),
    (VK_Name: 'VK_OEM_3'; VK_Description: 'Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the "`~" key'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: 'VK_OEM_4'; VK_Description: 'Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the "[{" key'),
    (VK_Name: 'VK_OEM_5'; VK_Description: 'Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the "\|" key'),
    (VK_Name: 'VK_OEM_6'; VK_Description: 'Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the "]}" key'),
    (VK_Name: 'VK_OEM_7'; VK_Description: 'Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the "single-quote/double-quote" key'),
    (VK_Name: 'VK_OEM_8'; VK_Description: 'Used for miscellaneous characters; it can vary by keyboard.'),
    (VK_Name: ''; VK_Description: 'Reserved'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: 'VK_OEM_102'; VK_Description: 'The <> keys on the US standard keyboard, or the \\| key on the non-US 102-key keyboard'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: 'VK_PROCESSKEY'; VK_Description: 'IME PROCESS key'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: 'VK_PACKET'; VK_Description: 'Used to pass Unicode characters as if they were keystrokes. The VK_PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods. For more information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP'),
    (VK_Name: ''; VK_Description: 'Unassigned'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: ''; VK_Description: 'OEM specific'),
    (VK_Name: 'VK_ATTN'; VK_Description: 'Attn key'),
    (VK_Name: 'VK_CRSEL'; VK_Description: 'CrSel key'),
    (VK_Name: 'VK_EXSEL'; VK_Description: 'ExSel key'),
    (VK_Name: 'VK_EREOF'; VK_Description: 'Erase EOF key'),
    (VK_Name: 'VK_PLAY'; VK_Description: 'Play key'),
    (VK_Name: 'VK_ZOOM'; VK_Description: 'Zoom key'),
    (VK_Name: 'VK_NONAME'; VK_Description: 'Reserved'),
    (VK_Name: 'VK_PA1'; VK_Description: 'PA1 key'),
    (VK_Name: 'VK_OEM_CLEAR'; VK_Description: 'Clear key')
  );

function VK_CodeInfo(const lVK_Code: Byte): TVK_KeyCode;
begin
  if InRange(lVK_Code, Low(cALL_KEY_CODES), High(cALL_KEY_CODES)) then
    Result := cALL_KEY_CODES[lVK_Code]
  else
  begin
    Result.VK_Name := 'OoR'; // Out of Range
    Result.VK_Description := 'Key code is out of range.';
  end;
end;

end.
